{
 "title": "Netatmo VS OpenWeather",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "netatmo_home_id",
    "query": {
     "query": "label_values(netatmo_outdoor_module_temperature, home_id)"
    }
   },
   {
    "name": "open_weather_id",
    "query": {
     "query": "label_values(open_weather_wind_speed, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "netatmo_outdoor_module_temperature{home_id=~\"$netatmo_home_id\"}",
     "legendFormat": "Netatmo {{home_name}} > {{module_name}}"
    },
    {
     "expr": "open_weather_main_temp{id=~\"$open_weather_id\"} - 273.15 # Convert Kelvin to Celsius",
     "legendFormat": "OpenWeather {{name}} temp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "netatmo_outdoor_module_humidity{home_id=~\"$netatmo_home_id\"}",
     "legendFormat": "Netatmo {{home_name}} > {{module_name}}"
    },
    {
     "expr": "open_weather_main_humidity{id=~\"$open_weather_id\"}",
     "legendFormat": "OpenWeather {{name}} humidity"
    }
   ]
  },
  {
   "title": "Wind Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "netatmo_wind_module_wind_strength{home_id=~\"$netatmo_home_id\"}",
     "legendFormat": "Netatmo {{home_name}} > {{module_name}}"
    },
    {
     "expr": "open_weather_wind_speed{id=~\"$open_weather_id\"}",
     "legendFormat": "OpenWeather {{name}} speed"
    }
   ]
  },
  {
   "title": "Wind Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "netatmo_wind_module_wind_angle{home_id=~\"$netatmo_home_id\"}",
     "legendFormat": "Netatmo {{home_name}} > {{module_name}}"
    },
    {
     "expr": "open_weather_wind_deg{id=~\"$open_weather_id\"}",
     "legendFormat": "OpenWeather {{name}} deg"
    }
   ]
  }
 ]
}