{
 "title": "Netatmo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Indoor Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_temperature",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_humidity",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_co2",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_pressure",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  {
   "title": "Absolute Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_absolute_pressure",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "netatmo_indoor_module_noise",
     "legendFormat": "{{home_name}} > {{station_name}}"
    }
   ]
  },
  { "title": "Outdoor Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "netatmo_outdoor_module_temperature",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "netatmo_outdoor_module_humidity",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  },
  { "title": "Wind Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Wind Angle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "netatmo_wind_module_wind_angle",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  },
  {
   "title": "Wind Strength",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "netatmo_wind_module_wind_strength",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  },
  {
   "title": "Gust Angle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "netatmo_wind_module_gust_angle",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  },
  {
   "title": "Gust Strength",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "netatmo_wind_module_gust_strength",
     "legendFormat": "{{home_name}} > {{module_name}}"
    }
   ]
  }
 ]
}