{
 "title": "Open Weather",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    { "expr": "open_weather_main_temp", "legendFormat": "{{name}} temp" },
    { "expr": "open_weather_main_feels_like", "legendFormat": "{{name}} feels like" },
    { "expr": "open_weather_main_temp_min", "legendFormat": "{{name}} temp min" },
    { "expr": "open_weather_main_temp_max", "legendFormat": "{{name}} temp max" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "open_weather_main_humidity", "legendFormat": "{{name}} humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "open_weather_main_pressure", "legendFormat": "{{name}} pressure" }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    { "expr": "open_weather_wind_speed", "legendFormat": "{{name}} speed" }
   ]
  },
  {
   "title": "Degree",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "open_weather_wind_deg", "legendFormat": "{{name}} deg" }
   ]
  },
  { "title": "Clouds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "open_weather_clouds_all", "legendFormat": "{{name}} all" }
   ]
  }
 ]
}